// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-oDMkASkryQXxprDenBXDS4VObvPrgo',
    appId: '1:411607502572:web:8220bab37a60b51a18dfc9',
    messagingSenderId: '411607502572',
    projectId: 'biapay-13ef3',
    authDomain: 'biapay-13ef3.firebaseapp.com',
    storageBucket: 'biapay-13ef3.firebasestorage.app',
    measurementId: 'G-HXG8SXJBCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVOUJnp3WK_tk8nan4ZhJUyugIkZtwK4',
    appId: '1:411607502572:android:ad72bb5028e67c5b18dfc9',
    messagingSenderId: '411607502572',
    projectId: 'biapay-13ef3',
    storageBucket: 'biapay-13ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnHcbc2rDXq_-dusYtTJxyho7qfg_tp5E',
    appId: '1:411607502572:ios:8e2a9528e80f1ac218dfc9',
    messagingSenderId: '411607502572',
    projectId: 'biapay-13ef3',
    storageBucket: 'biapay-13ef3.firebasestorage.app',
    iosBundleId: 'com.bianig.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnHcbc2rDXq_-dusYtTJxyho7qfg_tp5E',
    appId: '1:411607502572:ios:c0b3691862d662a518dfc9',
    messagingSenderId: '411607502572',
    projectId: 'biapay-13ef3',
    storageBucket: 'biapay-13ef3.firebasestorage.app',
    iosBundleId: 'com.bianig.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-oDMkASkryQXxprDenBXDS4VObvPrgo',
    appId: '1:411607502572:web:3be8eca97f04b82b18dfc9',
    messagingSenderId: '411607502572',
    projectId: 'biapay-13ef3',
    authDomain: 'biapay-13ef3.firebaseapp.com',
    storageBucket: 'biapay-13ef3.firebasestorage.app',
    measurementId: 'G-4RY08FCPH1',
  );
}
