class CountryCode {
  final String code;
  final String name;
  final String flag;
  final String dialCode;

  const CountryCode({
    required this.code,
    required this.name,
    required this.flag,
    required this.dialCode,
  });

  @override
  String toString() => '$flag $dialCode';
}

class CountryCodes {
  static final List<CountryCode> allCountries = [
    CountryCode(code: 'AF', name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93'),
    CountryCode(code: 'AL', name: 'Albania', flag: '🇦🇱', dialCode: '+355'),
    CountryCode(code: 'DZ', name: 'Algeria', flag: '🇩🇿', dialCode: '+213'),
    CountryCode(code: 'AD', name: 'Andorra', flag: '🇦🇩', dialCode: '+376'),
    CountryCode(code: 'AO', name: 'Angola', flag: '🇦🇴', dialCode: '+244'),
    CountryCode(code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', dialCode: '+1-268'),
    CountryCode(code: 'AR', name: 'Argentina', flag: '🇦🇷', dialCode: '+54'),
    CountryCode(code: 'AM', name: 'Armenia', flag: '🇦🇲', dialCode: '+374'),
    CountryCode(code: 'AU', name: 'Australia', flag: '🇦🇺', dialCode: '+61'),
    CountryCode(code: 'AT', name: 'Austria', flag: '🇦🇹', dialCode: '+43'),
    CountryCode(code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', dialCode: '+994'),
    CountryCode(code: 'BS', name: 'Bahamas', flag: '🇧🇸', dialCode: '+1-242'),
    CountryCode(code: 'BH', name: 'Bahrain', flag: '🇧🇭', dialCode: '+973'),
    CountryCode(code: 'BD', name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880'),
    CountryCode(code: 'BB', name: 'Barbados', flag: '🇧🇧', dialCode: '+1-246'),
    CountryCode(code: 'BY', name: 'Belarus', flag: '🇧🇾', dialCode: '+375'),
    CountryCode(code: 'BE', name: 'Belgium', flag: '🇧🇪', dialCode: '+32'),
    CountryCode(code: 'BZ', name: 'Belize', flag: '🇧🇿', dialCode: '+501'),
    CountryCode(code: 'BJ', name: 'Benin', flag: '🇧🇯', dialCode: '+229'),
    CountryCode(code: 'BT', name: 'Bhutan', flag: '🇧🇹', dialCode: '+975'),
    CountryCode(code: 'BO', name: 'Bolivia', flag: '🇧🇴', dialCode: '+591'),
    CountryCode(code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', dialCode: '+387'),
    CountryCode(code: 'BW', name: 'Botswana', flag: '🇧🇼', dialCode: '+267'),
    CountryCode(code: 'BR', name: 'Brazil', flag: '🇧🇷', dialCode: '+55'),
    CountryCode(code: 'BN', name: 'Brunei', flag: '🇧🇳', dialCode: '+673'),
    CountryCode(code: 'BG', name: 'Bulgaria', flag: '🇧🇬', dialCode: '+359'),
    CountryCode(code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226'),
    CountryCode(code: 'BI', name: 'Burundi', flag: '🇧🇮', dialCode: '+257'),
    CountryCode(code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', dialCode: '+238'),
    CountryCode(code: 'KH', name: 'Cambodia', flag: '🇰🇭', dialCode: '+855'),
    CountryCode(code: 'CM', name: 'Cameroon', flag: '🇨🇲', dialCode: '+237'),
    CountryCode(code: 'CA', name: 'Canada', flag: '🇨🇦', dialCode: '+1'),
    CountryCode(code: 'CF', name: 'Central African Republic', flag: '🇨🇫', dialCode: '+236'),
    CountryCode(code: 'TD', name: 'Chad', flag: '🇹🇩', dialCode: '+235'),
    CountryCode(code: 'CL', name: 'Chile', flag: '🇨🇱', dialCode: '+56'),
    CountryCode(code: 'CN', name: 'China', flag: '🇨🇳', dialCode: '+86'),
    CountryCode(code: 'CO', name: 'Colombia', flag: '🇨🇴', dialCode: '+57'),
    CountryCode(code: 'KM', name: 'Comoros', flag: '🇰🇲', dialCode: '+269'),
    CountryCode(code: 'CG', name: 'Congo', flag: '🇨🇬', dialCode: '+242'),
    CountryCode(code: 'CD', name: 'Congo (Democratic Republic)', flag: '🇨🇩', dialCode: '+243'),
    CountryCode(code: 'CR', name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506'),
    CountryCode(code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮', dialCode: '+225'),
    CountryCode(code: 'HR', name: 'Croatia', flag: '🇭🇷', dialCode: '+385'),
    CountryCode(code: 'CU', name: 'Cuba', flag: '🇨🇺', dialCode: '+53'),
    CountryCode(code: 'CY', name: 'Cyprus', flag: '🇨🇾', dialCode: '+357'),
    CountryCode(code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', dialCode: '+420'),
    CountryCode(code: 'DK', name: 'Denmark', flag: '🇩🇰', dialCode: '+45'),
    CountryCode(code: 'DJ', name: 'Djibouti', flag: '🇩🇯', dialCode: '+253'),
    CountryCode(code: 'DM', name: 'Dominica', flag: '🇩🇲', dialCode: '+1-767'),
    CountryCode(code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', dialCode: '+1-809'),
    CountryCode(code: 'EC', name: 'Ecuador', flag: '🇪🇨', dialCode: '+593'),
    CountryCode(code: 'EG', name: 'Egypt', flag: '🇪🇬', dialCode: '+20'),
    CountryCode(code: 'SV', name: 'El Salvador', flag: '🇸🇻', dialCode: '+503'),
    CountryCode(code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', dialCode: '+240'),
    CountryCode(code: 'ER', name: 'Eritrea', flag: '🇪🇷', dialCode: '+291'),
    CountryCode(code: 'EE', name: 'Estonia', flag: '🇪🇪', dialCode: '+372'),
    CountryCode(code: 'SZ', name: 'Eswatini', flag: '🇸🇿', dialCode: '+268'),
    CountryCode(code: 'ET', name: 'Ethiopia', flag: '🇪🇹', dialCode: '+251'),
    CountryCode(code: 'FJ', name: 'Fiji', flag: '🇫🇯', dialCode: '+679'),
    CountryCode(code: 'FI', name: 'Finland', flag: '🇫🇮', dialCode: '+358'),
    CountryCode(code: 'FR', name: 'France', flag: '🇫🇷', dialCode: '+33'),
    CountryCode(code: 'GA', name: 'Gabon', flag: '🇬🇦', dialCode: '+241'),
    CountryCode(code: 'GM', name: 'Gambia', flag: '🇬🇲', dialCode: '+220'),
    CountryCode(code: 'GE', name: 'Georgia', flag: '🇬🇪', dialCode: '+995'),
    CountryCode(code: 'DE', name: 'Germany', flag: '🇩🇪', dialCode: '+49'),
    CountryCode(code: 'GH', name: 'Ghana', flag: '🇬🇭', dialCode: '+233'),
    CountryCode(code: 'GR', name: 'Greece', flag: '🇬🇷', dialCode: '+30'),
    CountryCode(code: 'GD', name: 'Grenada', flag: '🇬🇩', dialCode: '+1-473'),
    CountryCode(code: 'GT', name: 'Guatemala', flag: '🇬🇹', dialCode: '+502'),
    CountryCode(code: 'GN', name: 'Guinea', flag: '🇬🇳', dialCode: '+224'),
    CountryCode(code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', dialCode: '+245'),
    CountryCode(code: 'GY', name: 'Guyana', flag: '🇬🇾', dialCode: '+592'),
    CountryCode(code: 'HT', name: 'Haiti', flag: '🇭🇹', dialCode: '+509'),
    CountryCode(code: 'HN', name: 'Honduras', flag: '🇭🇳', dialCode: '+504'),
    CountryCode(code: 'HU', name: 'Hungary', flag: '🇭🇺', dialCode: '+36'),
    CountryCode(code: 'IS', name: 'Iceland', flag: '🇮🇸', dialCode: '+354'),
    CountryCode(code: 'IN', name: 'India', flag: '🇮🇳', dialCode: '+91'),
    CountryCode(code: 'ID', name: 'Indonesia', flag: '🇮🇩', dialCode: '+62'),
    CountryCode(code: 'IR', name: 'Iran', flag: '🇮🇷', dialCode: '+98'),
    CountryCode(code: 'IQ', name: 'Iraq', flag: '🇮🇶', dialCode: '+964'),
    CountryCode(code: 'IE', name: 'Ireland', flag: '🇮🇪', dialCode: '+353'),
    CountryCode(code: 'IL', name: 'Israel', flag: '🇮🇱', dialCode: '+972'),
    CountryCode(code: 'IT', name: 'Italy', flag: '🇮🇹', dialCode: '+39'),
    CountryCode(code: 'JM', name: 'Jamaica', flag: '🇯🇲', dialCode: '+1-876'),
    CountryCode(code: 'JP', name: 'Japan', flag: '🇯🇵', dialCode: '+81'),
    CountryCode(code: 'JO', name: 'Jordan', flag: '🇯🇴', dialCode: '+962'),
    CountryCode(code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7'),
    CountryCode(code: 'KE', name: 'Kenya', flag: '🇰🇪', dialCode: '+254'),
    CountryCode(code: 'KI', name: 'Kiribati', flag: '🇰🇮', dialCode: '+686'),
    CountryCode(code: 'KP', name: 'North Korea', flag: '🇰🇵', dialCode: '+850'),
    CountryCode(code: 'KR', name: 'South Korea', flag: '🇰🇷', dialCode: '+82'),
    CountryCode(code: 'KW', name: 'Kuwait', flag: '🇰🇼', dialCode: '+965'),
    CountryCode(code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', dialCode: '+996'),
    CountryCode(code: 'LA', name: 'Laos', flag: '🇱🇦', dialCode: '+856'),
    CountryCode(code: 'LV', name: 'Latvia', flag: '🇱🇻', dialCode: '+371'),
    CountryCode(code: 'LB', name: 'Lebanon', flag: '🇱🇧', dialCode: '+961'),
    CountryCode(code: 'LS', name: 'Lesotho', flag: '🇱🇸', dialCode: '+266'),
    CountryCode(code: 'LR', name: 'Liberia', flag: '🇱🇷', dialCode: '+231'),
    CountryCode(code: 'LY', name: 'Libya', flag: '🇱🇾', dialCode: '+218'),
    CountryCode(code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423'),
    CountryCode(code: 'LT', name: 'Lithuania', flag: '🇱🇹', dialCode: '+370'),
    CountryCode(code: 'LU', name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352'),
    CountryCode(code: 'MG', name: 'Madagascar', flag: '🇲🇬', dialCode: '+261'),
    CountryCode(code: 'MW', name: 'Malawi', flag: '🇲🇼', dialCode: '+265'),
    CountryCode(code: 'MY', name: 'Malaysia', flag: '🇲🇾', dialCode: '+60'),
    CountryCode(code: 'MV', name: 'Maldives', flag: '🇲🇻', dialCode: '+960'),
    CountryCode(code: 'ML', name: 'Mali', flag: '🇲🇱', dialCode: '+223'),
    CountryCode(code: 'MT', name: 'Malta', flag: '🇲🇹', dialCode: '+356'),
    CountryCode(code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', dialCode: '+692'),
    CountryCode(code: 'MR', name: 'Mauritania', flag: '🇲🇷', dialCode: '+222'),
    CountryCode(code: 'MU', name: 'Mauritius', flag: '🇲🇺', dialCode: '+230'),
    CountryCode(code: 'MX', name: 'Mexico', flag: '🇲🇽', dialCode: '+52'),
    CountryCode(code: 'FM', name: 'Micronesia', flag: '🇫🇲', dialCode: '+691'),
    CountryCode(code: 'MD', name: 'Moldova', flag: '🇲🇩', dialCode: '+373'),
    CountryCode(code: 'MC', name: 'Monaco', flag: '🇲🇨', dialCode: '+377'),
    CountryCode(code: 'MN', name: 'Mongolia', flag: '🇲🇳', dialCode: '+976'),
    CountryCode(code: 'ME', name: 'Montenegro', flag: '🇲🇪', dialCode: '+382'),
    CountryCode(code: 'MA', name: 'Morocco', flag: '🇲🇦', dialCode: '+212'),
    CountryCode(code: 'MZ', name: 'Mozambique', flag: '🇲🇿', dialCode: '+258'),
    CountryCode(code: 'MM', name: 'Myanmar', flag: '🇲🇲', dialCode: '+95'),
    CountryCode(code: 'NE', name: 'Niger', flag: '🇳🇪', dialCode: '+227'),
    CountryCode(code: 'NG', name: 'Nigeria', flag: '🇳🇬', dialCode: '+234'),
    CountryCode(code: 'MK', name: 'North Macedonia', flag: '🇲🇰', dialCode: '+389'),
    CountryCode(code: 'NO', name: 'Norway', flag: '🇳🇴', dialCode: '+47'),
    CountryCode(code: 'OM', name: 'Oman', flag: '🇴🇲', dialCode: '+968'),
    CountryCode(code: 'PK', name: 'Pakistan', flag: '🇵🇰', dialCode: '+92'),
    CountryCode(code: 'PW', name: 'Palau', flag: '🇵🇼', dialCode: '+680'),
    CountryCode(code: 'PS', name: 'Palestine', flag: '🇵🇸', dialCode: '+970'),
    CountryCode(code: 'PA', name: 'Panama', flag: '🇵🇦', dialCode: '+507'),
    CountryCode(code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', dialCode: '+675'),
    CountryCode(code: 'PY', name: 'Paraguay', flag: '🇵🇾', dialCode: '+595'),
    CountryCode(code: 'PE', name: 'Peru', flag: '🇵🇪', dialCode: '+51'),
    CountryCode(code: 'PH', name: 'Philippines', flag: '🇵🇭', dialCode: '+63'),
    CountryCode(code: 'PL', name: 'Poland', flag: '🇵🇱', dialCode: '+48'),
    CountryCode(code: 'PT', name: 'Portugal', flag: '🇵🇹', dialCode: '+351'),
    CountryCode(code: 'QA', name: 'Qatar', flag: '🇶🇦', dialCode: '+974'),
    CountryCode(code: 'RO', name: 'Romania', flag: '🇷🇴', dialCode: '+40'),
    CountryCode(code: 'RU', name: 'Russia', flag: '🇷🇺', dialCode: '+7'),
    CountryCode(code: 'RW', name: 'Rwanda', flag: '🇷🇼', dialCode: '+250'),
    CountryCode(code: 'WS', name: 'Samoa', flag: '🇼🇸', dialCode: '+685'),
    CountryCode(code: 'SM', name: 'San Marino', flag: '🇸🇲', dialCode: '+378'),
    CountryCode(code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', dialCode: '+239'),
    CountryCode(code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', dialCode: '+966'),
    CountryCode(code: 'SN', name: 'Senegal', flag: '🇸🇳', dialCode: '+221'),
    CountryCode(code: 'RS', name: 'Serbia', flag: '🇷🇸', dialCode: '+381'),
    CountryCode(code: 'SC', name: 'Seychelles', flag: '🇸🇨', dialCode: '+248'),
    CountryCode(code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232'),
    CountryCode(code: 'SG', name: 'Singapore', flag: '🇸🇬', dialCode: '+65'),
    CountryCode(code: 'SK', name: 'Slovakia', flag: '🇸🇰', dialCode: '+421'),
    CountryCode(code: 'SI', name: 'Slovenia', flag: '🇸🇮', dialCode: '+386'),
    CountryCode(code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', dialCode: '+677'),
    CountryCode(code: 'SO', name: 'Somalia', flag: '🇸🇴', dialCode: '+252'),
    CountryCode(code: 'ZA', name: 'South Africa', flag: '🇿🇦', dialCode: '+27'),
    CountryCode(code: 'SS', name: 'South Sudan', flag: '🇸🇸', dialCode: '+211'),
    CountryCode(code: 'ES', name: 'Spain', flag: '🇪🇸', dialCode: '+34'),
    CountryCode(code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94'),
    CountryCode(code: 'SD', name: 'Sudan', flag: '🇸🇩', dialCode: '+249'),
    CountryCode(code: 'SR', name: 'Suriname', flag: '🇸🇷', dialCode: '+597'),
    CountryCode(code: 'SE', name: 'Sweden', flag: '🇸🇪', dialCode: '+46'),
    CountryCode(code: 'CH', name: 'Switzerland', flag: '🇨🇭', dialCode: '+41'),
    CountryCode(code: 'SY', name: 'Syria', flag: '🇸🇾', dialCode: '+963'),
    CountryCode(code: 'UA', name: 'Ukraine', flag: '🇺🇦', dialCode: '+380'),
    CountryCode(code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', dialCode: '+971'),
    CountryCode(code: 'GB', name: 'United Kingdom', flag: '🇬🇧', dialCode: '+44'),
    CountryCode(code: 'US', name: 'United States', flag: '🇺🇸', dialCode: '+1'),
    CountryCode(code: 'UY', name: 'Uruguay', flag: '🇺🇾', dialCode: '+598'),
    CountryCode(code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', dialCode: '+998'),
    CountryCode(code: 'VU', name: 'Vanuatu', flag: '🇻🇺', dialCode: '+678'),
    CountryCode(code: 'VA', name: 'Vatican City', flag: '🇻🇦', dialCode: '+379'),
    CountryCode(code: 'VE', name: 'Venezuela', flag: '🇻🇪', dialCode: '+58'),
    CountryCode(code: 'VN', name: 'Vietnam', flag: '🇻🇳', dialCode: '+84'),
    CountryCode(code: 'YE', name: 'Yemen', flag: '🇾🇪', dialCode: '+967'),
    CountryCode(code: 'ZM', name: 'Zambia', flag: '🇿🇲', dialCode: '+260'),
    CountryCode(code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263'),
  ];
}