class RouteList {
  RouteList._();
  static const String splash = '/splash';
  static const String initial = '/splash';
  static const String onBoardingScreen = '/onboarding';
  static const String createAccountScreen = '/create-account';
  static const String createAccountVerifyOtpScreen = '/verify-otp';
  static const String loginScreen = '/login';
  static const String getStarted = '/get-started';
  static const String bottomNavBar = '/home';
  static const String phoneRegScreen = '/phone-registration';
  static const String welcomeBackScreen = '/welcome-back';
  static const String forgotPassword = '/forgot-password';
  static const String forgotPasswordReset = '/forgot-password-reset';
  static const String airtime = '/airtime';
  static const String data = '/data';
  static const String cable = '/cable';
  static const String topUp = '/top-up';
  static const String sendMoneyTransfer = '/send-money';
  static const String sendMoneyToBank = '/send-to-bank';
  static const String amountPage = '/amount';
  static const String successScreen = '/success';
  static const String scannerOnboarding = '/scanner-onboarding';
  static const String qrScannerScreen = '/qr-scanner';
  static const String advancedScreen = '/advancedScreen';
  static const String cardTwo = '/cardTwo';
  static const String electricity = '/electricity';
  static const String requestAccountInfoScreen = '/requestAccountInfoScreen';
  static const String groupScreen = '/groupScreen';
  static const String privacyPolicyScreen = '/privacyPolicyScreen';
  static const String userKeysScreen = '/userKeysScreen';
  static const String notification = '/notification';
  static const String storageAndData = '/storageAndData';
  static const String securityNotificationScreen =
      '/securityNotificationScreen';
  static const String twoFactorVerificationScreen =
      '/TwoFactorVerificationScreen';
  static const String deleteAccountScreen = '/deleteAccountScreen';
  static const String chatBackupScreen = '/chatBackupScreen';
  static const String chatHistoryScreen = '/chatHistoryScreen';
  static const String helpCenter = '/helpCenter';
  static const String helpCenterMail = '/helpCenterMail';
  static const String helpCenterPhone = '/helpCenterPhone';
  static const String themeScreen = '/themeScreen';
  static const String wallpaperScreen = '/wallpaperScreen';
  static const String selectWallPaperScreen = '/selectWallPaperScreen';
  static const String contactSupportScreen = '/securityWarning';
  static const String profileChatKey = '/profileChatKey';
  static const String walletOnboarding = '/walletOnboarding';
  static const String verifyIdentityWallet = '/verifyIdentityWallet';
  static const String walletOtp = '/walletOtp';
  static const String qrScreen = '/qr-code';
  static const String setWalletPinScreen = '/setWalletPinScreen';
  static const String confirmSetWalletPinScreen = '/confirmSetWalletPinScreen';
  static const String walletScreen = '/walletScreen';
  static const String confirmWalletPinScreen = '/confirmWalletPinScreen';
  static const String transactionHistory = '/transaction-history';
  static const String changePaymentPin = '/change-pin';

  // static const String twoFactorPinScreenCode = '/twoFactorPinScreenCode';
  // static const String animatedonboarding = '/animatedonboarding';
}
